# Base configs
baseurl: "https://sajanphotography.github.io"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by Sajan"
subtitle: "See the world through my eyes!"
author: "Sajan"
header:
  title: "Photography"
  subtitle: "by Sajan"
footer:
  name: "Hey there, my name is Sajan"
  bio: "I have been working as a professional photographer for over 5 years. I specialize in portrait photography and provide my service for occasions like birthday celebrations, weddings,  party events, etc."
  github: 'Want my photography servece for your birthday party, wedding, rice feeding ceremony, party events, or maternity shoot? Call me at   <a href="tel:+491789321685">+491789321685</a> '
web_design: "AJ"
social_urls:
  facebook: "https://www.facebook.com/photosajan"
  twitter: "https://twitter.com/Sajanphotograp1"
  instagram: "https://www.instagram.com/sajanfotografie/"
  dribbble: ""
  linkedin: "https://www.linkedin.com/in/sajan-photography-653232199/"
  github: "https://www.github.com/Sajanphotography"
